url='https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv'
destination_folder='/tmp'
filename='inventory.csv'
account='WNHXTAP-GX22467'
warehouse='COMPUTE_WH'
database='TPCDS'
schema='RAW'
role='ACCOUNTADMIN'
file_format='COMMA_CSV'
stage='INV_STAGE'
table='INVENTORY'