-- rename the source columns
SELECT
    CD_DEP_EMPLOYED_COUNT AS DEP_EMPLOYED_COUNT,
    CD_DEMO_SK AS DEMO_SK,
    CD_DEP_COUNT AS DEP_COUNT,
    CD_CREDIT_RATING AS CREDIT_RATING,
    CD_EDUCATION_STATUS AS EDUCATION_STATUS,
    CD_PURCHASE_ESTIMATE AS PURCHASE_ESTIMATE,
    CD_MARITAL_STATUS AS MARITAL_STATUS,
    CD_DEP_COLLEGE_COUNT AS DEP_COLLEGE_COUNT,
    CD_GENDER AS GENDER
FROM 
    {{ source('tpcds', 'customer_demographics') }}