-- rename the source columns
SELECT
    CA_STREET_NAME AS STREET_NAME,
    CA_SUITE_NUMBER AS SUITE_NUMBER,
    CA_STATE AS STATE,
    CA_LOCATION_TYPE AS LOCATION_TYPE,
    CA_ADDRESS_SK AS ADDRESS_SK,
    CA_COUNTRY AS COUNTRY,
    CA_ADDRESS_ID AS ADDRESS_ID,
    CA_COUNTY AS COUNTY,
    CA_STREET_NUMBER AS STREET_NUMBER,
    CA_ZIP AS ZIP,
    CA_CITY AS CITY,
    CA_STREET_TYPE AS STREET_TYPE,
    CA_GMT_OFFSET AS GMT_OFFSET
FROM 
    {{ source('tpcds', 'customer_address') }}