{{
    config(
        target_database='tpcds',
        target_schema='staging',
        materialized='view'
    )
}}
-- rename the source columns
SELECT 
    CS_WAREHOUSE_SK AS WAREHOUSE_SK,
    CS_SHIP_DATE_SK AS SHIP_DATE_SK,
    CS_EXT_LIST_PRICE AS EXT_LIST_PRICE,
    CS_QUANTITY AS QUANTITY,
    CS_NET_PAID_INC_TAX AS NET_PAID_INC_TAX,
    CS_SOLD_TIME_SK AS SOLD_TIME_SK,
    CS_PROMO_SK AS PROMO_SK,
    CS_LIST_PRICE AS LIST_PRICE,
    CS_EXT_SHIP_COST AS EXT_SHIP_COST,
    CS_NET_PAID AS NET_PAID,
    CS_SOLD_DATE_SK AS SOLD_DATE_SK,
    CS_EXT_DISCOUNT_AMT AS EXT_DISCOUNT_AMT,
    CS_SHIP_ADDR_SK AS SHIP_ADDR_SK,
    CS_EXT_TAX AS EXT_TAX,
    CS_CATALOG_PAGE_SK AS CATALOG_PAGE_SK,
    CS_NET_PROFIT AS NET_PROFIT,
    CS_ITEM_SK AS ITEM_SK,
    CS_BILL_CDEMO_SK AS BILL_CDEMO_SK,
    CS_BILL_HDEMO_SK AS BILL_HDEMO_SK,
    CS_NET_PAID_INC_SHIP AS NET_PAID_INC_SHIP,
    CS_COUPON_AMT AS COUPON_AMT,
    CS_NET_PAID_INC_SHIP_TAX AS NET_PAID_INC_SHIP_TAX,
    CS_ORDER_NUMBER AS ORDER_NUMBER,
    CS_EXT_WHOLESALE_COST AS EXT_WHOLESALE_COST,
    CS_SHIP_MODE_SK AS SHIP_MODE_SK,
    CS_EXT_SALES_PRICE AS EXT_SALES_PRICE,
    CS_SHIP_CUSTOMER_SK AS SHIP_CUSTOMER_SK,
    CS_BILL_ADDR_SK AS BILL_ADDR_SK,
    CS_SHIP_CDEMO_SK AS SHIP_CDEMO_SK,
    CS_SHIP_HDEMO_SK AS SHIP_HDEMO_SK,
    CS_WHOLESALE_COST AS WHOLESALE_COST,
    CS_SALES_PRICE AS SALES_PRICE,
    CS_CALL_CENTER_SK AS CALL_CENTER_SK,
    CS_BILL_CUSTOMER_SK AS BILL_CUSTOMER_SK,    
    _AIRBYTE_NORMALIZED_AT
FROM 
    {{ source('tpcds', 'catalog_sales') }}
