-- rename the source columns
SELECT 
    C_SALUTATION AS SALUTATION,
    C_PREFERRED_CUST_FLAG AS PREFERRED_CUST_FLAG,
    C_FIRST_SALES_DATE_SK AS FIRST_SALES_DATE_SK,
    C_CUSTOMER_SK AS CUSTOMER_SK,
    C_LOGIN AS LOGIN,
    C_CURRENT_CDEMO_SK AS CURRENT_CDEMO_SK,
    C_FIRST_NAME AS FIRST_NAME,
    C_CURRENT_HDEMO_SK AS CURRENT_HDEMO_SK,
    C_CURRENT_ADDR_SK AS CURRENT_ADDR_SK,
    C_LAST_NAME AS LAST_NAME,
    C_CUSTOMER_ID AS CUSTOMER_ID,
    C_LAST_REVIEW_DATE_SK AS LAST_REVIEW_DATE_SK,
    C_BIRTH_MONTH AS BIRTH_MONTH,
    C_BIRTH_COUNTRY AS BIRTH_COUNTRY,
    C_BIRTH_YEAR AS BIRTH_YEAR,
    C_BIRTH_DAY AS BIRTH_DAY,
    C_EMAIL_ADDRESS AS EMAIL_ADDRESS,
    C_FIRST_SHIPTO_DATE_SK AS FIRST_SHIPTO_DATE_SK, 
    _AIRBYTE_NORMALIZED_AT
FROM {{ source('tpcds', 'customer') }}