{{
    config (
        materialized = 'incremental',
        unique_key = ['CUSTOMER_SK', 'START_DATE', 'END_DATE'],
        target_schema = 'analytics',
        target_database = 'tpcds'
    )
}}
-- pull custome attributes together
SELECT DISTINCT
    IC.SALUTATION AS SALUTATION,
    IC.PREFERRED_CUST_FLAG AS PREFERRED_CUST_FLAG,
    IC.FIRST_SALES_DATE_SK AS FIRST_SALES_DATE_SK,
    IC.CUSTOMER_SK AS CUSTOMER_SK,
    IC.LOGIN AS LOGIN,
    IC.CURRENT_CDEMO_SK AS CURRENT_CDEMO_SK,
    IC.FIRST_NAME AS FIRST_NAME,
    IC.CURRENT_HDEMO_SK AS CURRENT_HDEMO_SK,
    IC.CURRENT_ADDR_SK AS CURRENT_ADDR_SK,
    IC.LAST_NAME AS LAST_NAME,
    IC.CUSTOMER_ID AS CUSTOMER_ID,
    IC.LAST_REVIEW_DATE_SK AS LAST_REVIEW_DATE_SK,
    IC.BIRTH_MONTH AS BIRTH_MONTH,
    IC.BIRTH_COUNTRY AS BIRTH_COUNTRY,
    IC.BIRTH_YEAR AS BIRTH_YEAR,
    IC.BIRTH_DAY AS BIRTH_DAY,
    IC.EMAIL_ADDRESS AS EMAIL_ADDRESS,
    IC.FIRST_SHIPTO_DATE_SK AS FIRST_SHIPTO_DATE_SK,
    RCA.STREET_NAME AS STREET_NAME,
    RCA.SUITE_NUMBER AS SUITE_NUMBER,
    RCA.STATE AS STATE,
    RCA.LOCATION_TYPE AS LOCATION_TYPE,
    RCA.COUNTRY AS COUNTRY,
    RCA.ADDRESS_ID AS ADDRESS_ID,
    RCA.COUNTY AS COUNTY,
    RCA.STREET_NUMBER AS STREET_NUMBER,
    RCA.ZIP AS ZIP,
    RCA.CITY AS CITY,
    RCA.GMT_OFFSET AS GMT_OFFSET,
    RCD.DEP_EMPLOYED_COUNT AS DEP_EMPLOYED_COUNT,
    RCD.DEP_COUNT AS DEP_COUNT,
    RCD.CREDIT_RATING AS CREDIT_RATING,
    RCD.EDUCATION_STATUS AS EDUCATION_STATUS,
    RCD.PURCHASE_ESTIMATE AS PURCHASE_ESTIMATE,
    RCD.MARITAL_STATUS AS MARITAL_STATUS,
    RCD.DEP_COLLEGE_COUNT AS DEP_COLLEGE_COUNT,
    RCD.GENDER AS GENDER,
    RHD.BUY_POTENTIAL AS BUY_POTENTIAL,
    RHD.VEHICLE_COUNT AS VEHICLE_COUNT,
    RHD.INCOME_BAND_SK AS INCOME_BAND_SK,
    RI.LOWER_BOUND AS LOWER_BOUND,
    RI.UPPER_BOUND AS UPPER_BOUND,
    IC.DBT_VALID_FROM AS START_DATE,
    IC.DBT_VALID_TO AS END_DATE
 FROM {{ ref('customer_snapshot')}} AS IC
 LEFT JOIN {{ ref('stg_tpcds__customer_address')}} AS RCA 
    ON IC.CURRENT_ADDR_SK = RCA.ADDRESS_SK
 LEFT JOIN {{ ref('stg_tpcds__customer_demographics')}} AS RCD 
    ON IC.CURRENT_CDEMO_SK = RCD.DEMO_SK
 LEFT JOIN {{ ref('stg_tpcds__household_demographics')}} AS RHD 
    ON IC.CURRENT_HDEMO_SK = RHD.DEMO_SK
 LEFT JOIN {{ ref('stg_tpcds__income_band')}} AS RI 
    ON RHD.INCOME_BAND_SK = RI.INCOME_BAND_SK
-- keep both the old and new records in the table, so comment out below filter
-- WHERE IC.DBT_VALID_TO IS NULL